services:

  agent-framework-quick-start:
    image: dotnet-ai/agent-framework-quick-start
    build:
      context: .
      dockerfile: src/AgentFrameworkQuickStart/Dockerfile
    container_name: agent-framework-quick-start
    ports:
    - "5200:5200"
    - "5201:5201"

  web-app:
    image: dotnet-ai/webapp
    build:
      context: .
      dockerfile: src/WebApp/Dockerfile
    container_name: webapp
    ports:
    - "5000:5000"
    - "5001:5001"
