<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>f38ab780-bbc6-4763-ad50-d23564eeb1f4</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="A2A.AspNetCore" />
    <PackageReference Include="Microsoft.Agents.AI.Hosting" />
    <PackageReference Include="Microsoft.Agents.AI.Hosting.A2A.AspNetCore" />
    <PackageReference Include="Microsoft.Agents.AI.OpenAI" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.Extensions.AI.Ollama" />
    <PackageReference Include="Scalar.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ServiceDefaults\ServiceDefaults.csproj" />
    <ProjectReference Include="..\SharedKernel\SharedKernel.csproj" />
  </ItemGroup>

</Project>
