apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-framework-quick-start-config
  labels:
    app: agent-framework-quick-start
  namespace: dotnet-ai
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  ASPNETCORE_HTTP_PORTS: "5002"
  ASPNETCORE_URLS: "http://+:5002"
  AgentFrameworkQuickStart__BaseUrl: "http://agent-framework-quick-start:5002"